package ch.usi.ict.dev.AclOverSoapHttpMP;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

//import org.apache.cxf.annotations.SchemaValidation;

/**
 * This class was generated by Apache CXF 2.3.2
 * 2011-07-20T12:00:59.580+02:00
 * Generated source version: 2.3.2
 * 
 */
 
@WebService(targetNamespace = "http://www.usi.ch/ict/dev/AclOverSoapHttpMP/", name = "AclOverSoapHttpMPInterface")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
//@SchemaValidation
public interface AclOverSoapHttpMPInterface {

    @Oneway
    @WebMethod(action = "http://www.usi.ch/ict/dev/AclOverSoapHttpMP/sendMessage")
    public void sendMessage(
        @WebParam(partName = "message", name = "acl-message", targetNamespace = "http://www.usi.ch/ict/dev/AclOverSoapHttpMP/")
        AclMessage message
    );
}
