
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ch.usi.ict.dev.AclOverSoapHttpMP;

import java.util.logging.Logger;

import ch.usi.ict.dev.AclOverSoapHttpMP.components.MessageInBoxAdapter;

/**
 * This class was generated by Apache CXF 2.3.2
 * 2011-01-27T17:10:53.456+01:00
 * Generated source version: 2.3.2
 * 
 */

@javax.jws.WebService(
                      serviceName       = "AclOverSoapHttpMPService",
                      portName          = "AclOverSoapHttpMPPort",
                      targetNamespace   = "http://www.usi.ch/ict/dev/AclOverSoapHttpMP/",
                      wsdlLocation      = "wsdl/AclOverSoapHttpMP.wsdl",
                      endpointInterface = "ch.usi.ict.dev.AclOverSoapHttpMP.AclOverSoapHttpMPInterface")
                      
public class AclOverSoapHttpMPInterfaceImpl implements AclOverSoapHttpMPInterface {

	private MessageInBoxAdapter inbox    = null; 
	private static final Logger LOG      = Logger.getLogger(AclOverSoapHttpMPInterfaceImpl.class.getName());
    
    
	public AclOverSoapHttpMPInterfaceImpl() {
	}
    
    public AclOverSoapHttpMPInterfaceImpl (MessageInBoxAdapter inbox) {	
    	this.inbox = inbox;	
    }
    

    /**
     * TODO Split Message over the intended-receiver
     *  (non-Javadoc)
     * @see ch.usi.ict.dev.AclOverSoapHttpMP.AclOverSoapHttpMPInterface#sendMessage(ch.usi.ict.dev.AclOverSoapHttpMP.AclMessage  message )*
     */
    public void sendMessage(AclMessage message) { 
        
    	LOG.info("Executing operation sendMessage");
        
        if (inbox != null)
        	/**TODO Split Message over the incoming intended-receiver*/
        	inbox.postMsg(message);// This method must be thread safe.
        else
        	System.err.println("No message dispatcher");
        
    }

}
