
/*
 * 
 */

package ch.usi.ict.dev.AclOverSoapHttpMP;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.2
 * 2011-07-20T12:00:59.675+02:00
 * Generated source version: 2.3.2
 * 
 */


@WebServiceClient(name = "AclOverSoapHttpMPService", 
                  wsdlLocation = "http://localhost:8080/ACLSoapOverHttpMP/services/AclOverSoapHttpMPPort?wsdl",
                  targetNamespace = "http://www.usi.ch/ict/dev/AclOverSoapHttpMP/") 
public class AclOverSoapHttpMPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.usi.ch/ict/dev/AclOverSoapHttpMP/", "AclOverSoapHttpMPService");
    public final static QName AclOverSoapHttpMPPort = new QName("http://www.usi.ch/ict/dev/AclOverSoapHttpMP/", "AclOverSoapHttpMPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ACLSoapOverHttpMP/services/AclOverSoapHttpMPPort?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/ACLSoapOverHttpMP/services/AclOverSoapHttpMPPort?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AclOverSoapHttpMPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AclOverSoapHttpMPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AclOverSoapHttpMPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns AclOverSoapHttpMPInterface
     */
    @WebEndpoint(name = "AclOverSoapHttpMPPort")
    public AclOverSoapHttpMPInterface getAclOverSoapHttpMPPort() {
        return super.getPort(AclOverSoapHttpMPPort, AclOverSoapHttpMPInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AclOverSoapHttpMPInterface
     */
    @WebEndpoint(name = "AclOverSoapHttpMPPort")
    public AclOverSoapHttpMPInterface getAclOverSoapHttpMPPort(WebServiceFeature... features) {
        return super.getPort(AclOverSoapHttpMPPort, AclOverSoapHttpMPInterface.class, features);
    }

}
